services:
  backend:
    image: node:18
    tty: true
    stdin_open: true
    restart: always
    env_file:
      - ./.env
    working_dir: /destination-app/backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: sh -c "npm install && npm run dev"
    volumes:
      - .:/destination-app/backend # Mount the local code into the container
      - /destination-app/backend/node_modules # Prevent overriding node_modules

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  tests:
    image: node:18
    env_file:
      - ./.env
    working_dir: /destination-app/backend
    depends_on:
      - db
    command: sh -c "npm install && npm run test"
    volumes:
      - .:/destination-app/backend
      - /destination-app/backend/node_modules
#Need script in yml file to run migrations when push to main (pipeline) to update prod db
  migrations:
    image: node:18
    env_file:
      - ./.env
    depends_on:
      - db
    command: sh -c "apt-get update && apt-get install -y postgresql-client && npm install && ./runMigrations.sh"
    working_dir: /destination-app/backend
    volumes:
      - .:/destination-app/backend
      - /destination-app/backend/node_modules

volumes:
  db-data:
