name: Database Migrations

on:
  push:
    branches:
      - main

jobs:
  run-migrations:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Run migrations
        run: |
          cd backend
          chmod +x runMigrations.sh
          DB_HOST=${{ secrets.PROD_DB_HOST }} \
          DB_USER=${{ secrets.PROD_DB_USER }} \
          DB_PASSWORD=${{ secrets.PROD_DB_PASSWORD }} \
          DB_NAME=${{ secrets.PROD_DB_NAME }} \
          ./runMigrations.sh
        env:
          NODE_ENV: production 