name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install and Test Backend
        run: |
          cd backend
          npm install
          npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          cd backend
          npm install
          
      - name: Build
        run: |
          cd backend
          npm run build
          
      - name: Configure AWS Credentials
        env:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
          aws-region: eu-west-2
        run: |
          echo "AWS credentials configured from environment variables"
          
      - name: Deploy Lambda Functions
        working-directory: backend
        run: |
          zip -j country-function.zip ./dist/src/handlers/country-service-handler.js*
          zip -j tourism-function.zip ./dist/src/handlers/tourism-service-handler.js*
          zip -j earthquake-function.zip ./dist/src/handlers/earthquake-service-handler.js*
          zip -j volcano-function.zip ./dist/src/handlers/volcano-service-handler.js*
          
          aws lambda update-function-code \
            --function-name getCountryService \
            --zip-file fileb://country-function.zip
            
          aws lambda update-function-code \
            --function-name getTourismService \
            --zip-file fileb://tourism-function.zip
            
          aws lambda update-function-code \
            --function-name getEarthquakeService \
            --zip-file fileb://earthquake-function.zip
            
          aws lambda update-function-code \
            --function-name getVolcanoService \
            --zip-file fileb://volcano-function.zip
