name: Deploying Lambdas
#every time any code is pushed on the main branch, this workflow will run
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      
permissions:
  id-token: write 
  contents: read 

jobs:
  lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - name: Install dependencies and Build
        run: |
          cd backend
          npm install
          npm run build
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::390403869591:role/GitHubActionsRole
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Zip the Lambda function
        run: zip -r lambda-function.zip ./backend/dist/ ./backend/node_modules/
      - name: Upload ZIP to S3
        run: aws s3 cp lambda-function.zip s3://destination-lambda-deploy-storage/lambda-function.zip
      - name: Deploy Lambda Functions
        run: |
          aws lambda update-function-code --function-name=getCountryService --s3-bucket destination-lambda-deploy-storage --s3-key lambda-function.zip
          aws lambda update-function-code --function-name=getEarthquakeService --s3-bucket destination-lambda-deploy-storage --s3-key lambda-function.zip
          aws lambda update-function-code --function-name=getTourismService --s3-bucket destination-lambda-deploy-storage --s3-key lambda-function.zip
          aws lambda update-function-code --function-name=getVolcanoService --s3-bucket destination-lambda-deploy-storage --s3-key lambda-function.zip
