name: Deploy Lambdas

on:
  push:
    branches:
      - main
    paths:
      - 'backend/src/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd backend
          npm install
          
      - name: Build
        run: |
          cd backend
          npm run build
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          
      - name: Deploy Lambda Functions
        working-directory: backend
        run: |
          zip -j country-function.zip ./dist/src/handlers/country-service-handler.js*
          zip -j tourism-function.zip ./dist/src/handlers/tourism-service-handler.js*
          zip -j earthquake-function.zip ./dist/src/handlers/earthquake-service-handler.js*
          zip -j volcano-function.zip ./dist/src/handlers/volcano-service-handler.js*
          
          aws lambda update-function-code \
            --function-name getCountryService \
            --zip-file fileb://country-function.zip
            --region eu-west-2
            
          aws lambda update-function-code \
            --function-name getTourismService \
            --zip-file fileb://tourism-function.zip \
            --region eu-west-2
            
          aws lambda update-function-code \
            --function-name getEarthquakeService \
            --zip-file fileb://earthquake-function.zip \
            --region eu-west-2
            
          aws lambda update-function-code \
            --function-name getVolcanoService \
            --zip-file fileb://volcano-function.zip \
            --region eu-west-2
