name: Deploying Lambdas
#every time any code is pushed on the main branch, this workflow will run
on:
  push:
    branches:
      - main
jobs:
  lambda1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - name: Install dependencies and Build
        run: |
          cd backend
          npm install
          npm run build
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: zip -j country-function.zip ./dist/src/handlers/country-service-handler.js*
      - run: aws lambda update-function-code --function-name=getCountryService --zip-file=fileb://country-function.zip
