name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'  

permissions:
  id-token: write 
  contents: read 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies and Build
        env:
          VITE_COUNTRY_API_URL: ${{ secrets.VITE_COUNTRY_API_URL }}
          VITE_TOURISM_API_URL: ${{ secrets.VITE_TOURISM_API_URL }}
          VITE_EARTHQUAKE_API_URL: ${{ secrets.VITE_EARTHQUAKE_API_URL }}
          VITE_VOLCANO_API_URL: ${{ secrets.VITE_VOLCANO_API_URL }}
        run: |
          cd frontend
    
          echo "VITE_USE_MOCK_DATA=false" > .env.production
          echo "VITE_COUNTRY_API_URL=$VITE_COUNTRY_API_URL" >> .env.production
          echo "VITE_TOURISM_API_URL=$VITE_TOURISM_API_URL" >> .env.production
          echo "VITE_EARTHQUAKE_API_URL=$VITE_EARTHQUAKE_API_URL" >> .env.production
          echo "VITE_VOLCANO_API_URL=$VITE_VOLCANO_API_URL" >> .env.production
          echo "VITE_LOCAL_API_URL=http://localhost:8080/api" >> .env.production

          echo "Environment file contents:"
          cat .env.production
          
          npm install
          npm run build

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::390403869591:role/GitHubActionsRole
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync frontend/dist/ s3://${{ secrets.S3_BUCKET }} --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*" 